### ISSUE TITLE
[Bug]:  issue with connecting repo

### ISSUE THREAD

**Issue by IamAliBaba** [alcionai/corso#3770] opened 2023-07-09 16:36 UTC
### What happened?

When first time doint corso init from powershell terminal , after that its not possible to connect from bash.

getting error that password is not correct.

Talk is about  S3 compliant storage provider.

### Corso Version?

Corso v0.10.0

### Where are you running Corso?

powershell and bash

**Comment by ryanfkeepers** [comment] 2023-07-10 03:24
Hi @IamAliBaba, thanks for the ticket. If you could help us out a bit, a few extra details would be helpful for us here.  First: can you double check that your bash terminal has the same `CORSO_PASSPHRASE` entry that you used with powershell?

Second, can you please print out the error message you received from corso on the bash run?  Getting the complete logs would be the best way for us to debug the issue, but the error itself will be a good starting point.  

Thank you!

**Comment by IamAliBaba** [comment] 2023-07-10 06:47
here is the error.

Error: connecting to the S3 repository: connecting kopia client: connecting to repo: unable to create format manager: invalid repository password

**Comment by neha-Gupta1** [comment] 2023-07-10 14:45
@IamAliBaba just to confirm. The envar which you are exposing is - `CORSO_PASSPHRASE` and not `CORSO_PASSWORD`.

**Comment by IamAliBaba** [comment] 2023-07-10 14:47
sorry:

CORSO_PASSPHRASE

**Comment by IamAliBaba** [comment] 2023-07-10 16:41
i do export with required key=vales
<img width="985" alt="image" src="https://github.com/alcionai/corso/assets/26478599/d73195bf-6a95-4c95-b34b-9ba5a8376e2b">

<img width="1062" alt="image" src="https://github.com/alcionai/corso/assets/26478599/72d3e642-8873-401e-9087-419c813c3141">

**Comment by ntolia** [comment] 2023-07-10 16:47
@IamAliBaba Given that you inited the repo using PS, can you do a new repo init using bash and see if you run into the same error? I wonder if there were newlines or other special characters that got accidentally added to your passphrase when doing a repo init.

**Comment by IamAliBaba** [comment] 2023-07-10 16:49
it says already inited and again the same issue.

is it possible to change PASSPHRASE for  already encrypted data ?

**Comment by neha-Gupta1** [comment] 2023-07-11 06:29
@IamAliBaba to get some more clarification, 
can you try both these below commands in bash,
`corso repo init s3 --bucket <your_bucket_name> --prefix <some_prefix> --endpoint <value> --disable-tls`

and in same bash, run-
`corso repo connect s3 --bucket <your_bucket_name> --prefix <some_prefix> --endpoint <value> --disable-tls`

do you still see the same error? This is to confirm that you are getting the error while using two different terminal or you see errors on same terminal too.

**Comment by neha-Gupta1** [comment] 2023-07-11 10:06
The best possible reason is any extra character getting inserted in the `CORSO_PASSPHRASE`. I am able to reproduce your issue if I change/alter the `CORSO_PASSPHRASE` value.

**Comment by neha-Gupta1** [comment] 2023-07-12 07:34
Tried reproducing on powershell. But as you mentioned,
![powershell_working](https://github.com/alcionai/corso/assets/23420056/9b603595-2e72-43a4-aa05-ab88c64ecd45)
running connect in powershell worked fine. 

Then on **changing** the passphrase value-
![wrong_powershell](https://github.com/alcionai/corso/assets/23420056/a1b48596-3e05-4420-af84-0b739cdab0fc)
getting the same error as you get.

**Comment by IamAliBaba** [comment] 2023-07-12 08:20
i just changed the passphrase value and it works .

Seems it had $ sign and its wasnt recognized correctly.

One more question .

Is it possible to change current passphrase for already encrypted blob container?

**Comment by neha-Gupta1** [comment] 2023-07-12 15:36
At the moment its not possible to change passphrase for an initiated repo. But we plan to take it in the future.

**Comment by gmatev** [comment] 2023-07-12 17:28
@IamAliBaba the kopia operation should allow you to change the password as @ntolia indicated., 

Not sure if you have gotten around the original issue, but I believe the following has happened in your case. 

In PS you set the envar as follows
  ```
   $env:CORSO_PASSPHRASE="SOME$PASS"
```
Because of the quoting PS would try to expand `$PASS` as a variable which will likely be empty. In reality you will be setting your passphrase to `SOME`. 

To get into the repo from bash you should be able to just use that as the passphrase. To prevent this issue, set in PS using `$env:CORSO_PASSPHRASE='SOME$PASS'`

Hope this helps

**Comment by ntolia** [comment] 2023-07-14 05:56
Closing this but there is a docs patch out for review to fix this issue in the docs too - https://github.com/alcionai/corso/pull/3796

**Closed by ntolia** 2023-07-14 05:56 UTC
Labels: bug
