### ISSUE TITLE
Properly handle cases of duplicate folder names 

### ISSUE THREAD

**Issue by gmatev** [alcionai/corso#3197] opened 2023-04-21 18:44 UTC
For context on this see Corso Discord discussion - https://discord.com/channels/1022200980487557130/1022200981376745474/1098987178232651859

seems to be related to clients misbehaving and creating the duplicates. In this case this seemed to be "Detected Items" which seems like an known issue - https://forum.eset.com/topic/22459-outlook-detected-items-folder-behaving-strangely/

Should have a way of handling this case more gracefully. Given that this generally does not play well with Exchange and Outlook (See reports on crashes), I don't think it needs to be fully supported in a comprehensive way but some treatment that does not result in failed backups is desirable. 

Basic options:
* Pick the first occurrence only
* Pick the occurrence with most items only
* Handle explicitly "Detected items" - obviously not reliable

More comprehensive:
* Treat duplicate folders at the same level as a single folder for backup (merge). In place restores will go to the first occurrence

**Comment by ashmrtn** [comment] 2023-05-01 22:24
The more I think about this, the more wary I become of it from an implementation standpoint. It feels like all of the options given above make assumptions about how the data will evolve over time. Given that we have no reproducer of this, we're kind of guessing as to what behavior we'll see as things more forward

Below are some notes about potential issues we could run into as state evolves across backups

>Pick the first occurrence only

We'd need a clear definition of what "first" means. Would it be the one with the lexicographically lesser ID? We need some stable way to determine across backups. Also what happens if the "first" one we chose is deleted? Does the remaining one replace it entirely?


>Pick the occurrence with most items only

This assumes that the one we pick will always have the most items. If at some point it doesn't have the most items then we'll pick the other one, but may also fail to remove the items from the other one in the previous backup because we won't know we picked the other one on the previous backup

>Handle explicitly "Detected items" - obviously not reliable

yea, this seems tough to do and there's possibly other cases we'd run into this besides just something called "Detected items"

>Treat duplicate folders at the same level as a single folder for backup (merge). In place restores will go to the first occurrence

Unfortunately, if we merge them into a single `BackupCollection` struct in Corso (i.e. the Graph Connector code does the detection and merging), I think we'll end up with duplicate/zombie items if one of the folders is moved/deleted/renamed. The reasoning behind this is it won't be clear _which_ items should be removed from the merged collection (kopia folder) when one of the duplicate Exchange folders it moved/deleted/renamed. On folder moves/deletions/renames, only the folder object that Graph returns is changed. The items in the folder aren't returned at all so we have no way to determine what stays and what goes. Unless the entire folder(s) is(are) refetched, there's no way to get rid of the duplicate/zombie items. They'll continue to be brought forward on each incremental backup

**Closed** 2023-05-11 23:07 UTC
Labels: community-request
