### ISSUE TITLE
[Bug]: kopia error with corso version 0.7.0 

### ISSUE THREAD

**Issue by abaldoni** [alcionai/corso#3344] opened 2023-05-08 10:30 UTC
### What happened?

During backup the following error is generated (no errors with version 0.6.1, the destination repository was created with corso 0.6.0 and it already contains other backups):

Error: running backup: persisting collection backups: building kopia snapshot

### Corso Version?

Corso v0.7.0

### Where are you running Corso?

VMware Photon OS 4 x86_64 
Storage provided by local minio version RELEASE.2023-05-04T21-44-30Z

### Relevant log output

```shell
corso backup create onedrive --user foo@bar.baz --log-level backup
Logging to file: /home/corso/.cache/corso/logs/2023-05-08T10-05-37Z.log
Connecting to repository:      0s done
Connecting to M365:         done
Backing Up ∙ foo@bar.baz
Discovering items to backup:      2s done
∙ files:      1s done
Discovered 66 items to backup
Backing up data:      5s done
Error: running backup: persisting collection backups: building kopia snapshot

Completed Backups:
No backups available
Error: 1 of 1 backups failed:
∙ foo@bar.baz: running backup: persisting collection backups: building kopia snapshot
```

**Comment by ryanfkeepers** [comment] 2023-05-08 19:07
Hi @abaldoni, thanks for the bug report!  We're going to need a couple more details in order to dig into the cause here, primarily the log file itself `/home/corso/.cache/corso/logs/2023-05-08T10-05-37Z.log` (or relevant snippets of it).

If you'd like to join us on discord (https://discord.gg/ewuWryaj), we can discuss this with you live, plus get a secure transfer of that info.

**Comment by heimdal-31** [comment] 2023-05-08 20:30
I have seen the same.  Sharepoint backups only.  Repo created with 0.6.1.  7.0 client gives the same error.  Error details seem to indicate it is not handling a 302 correctly:

 "error": "sharepoint reader: non-2xx http response: 302 Found", "errorVerbose": "302 Found\n\t/home/runner/work/corso/corso/src/internal/connector/onedrive/item.go:167\nnon-2xx http response\n\t/home/runner/work/corso/corso/src/internal/connector/onedrive/item.go:167\nsharepoint reader\n\t/home/runner/work/corso/corso/src/internal/connector/onedrive/item.go:40", "error_labels": {"status_code_302":{}}}
2023-05-08T20:22:55.903Z        INFO    graph/middleware.go:158 graph api error: 302 Found

I also get the same trying to backup a new SharePoint site with the 7.0 client.  Backup fails and it is the same 302 errors.  I have not experimented with anything other that SharePoint backups with 7.0.

**Comment by ryanfkeepers** [comment] 2023-05-08 20:45
Thanks, @heimdal-31, the extra info is appreciated.  You're also welcome to join us on discord if you'd like to keep up with the live debugging!

**Comment by ntolia** [comment] 2023-05-10 02:58
@heimdal-31 We believe we have a fix. Would you be able to give this build a try - https://github.com/alcionai/corso/actions/runs/4931200365 and see if it solves the issue?

**Comment by heimdal-31** [comment] 2023-05-10 20:33
@ntolia I can confirm that this has addressed my issues with existing backups and with new ones.  Thanks!

**Comment by ntolia** [comment] 2023-05-10 20:39
Amazing @heimdal-31, really appreciate the debug logs and support from you and @abaldoni! Given that @abaldoni also reported success on Discord, I am going to close this one out. v0.8.0 will have the fix when it comes out.

@ryanfkeepers Thanks for the quick turnaround on this!

**Closed by ntolia** 2023-05-10 20:39 UTC
Labels: bug
