### ISSUE TITLE
[Bug]: Repo connect fails with "unsupported account provider" error

### ISSUE THREAD

**Issue by pandeyabs** [alcionai/corso#3856] opened 2023-07-19 22:06 UTC
### What happened?

When configuration is supplied through env vars, connecting to an existing repo fails with `Error: retrieving account configuration details: unsupported account provider`

More observations: 
* We don't see this error if we supply configuration using a config file `.corso.toml`
* Not seen with v0.10.0. This is a regression. 

### Corso Version?

Corso v0.11.0

### Where are you running Corso?

Linux

### Relevant log output
With env variables set, run 
`./corso repo connect s3 --bucket test_bucket` 

**With v0.10.0 - successful**

**With v0.11.0 - fails**
`Error: retrieving account configuration details: unsupported account provider`

**With v0.11.0 + .corso.toml - successful**

**Comment by vkamra** [comment] 2023-07-20 01:25
The issue is that [this](https://github.com/alcionai/corso/blob/main/src/cli/config/storage.go#L80) check will fail if `matchFromConfig` is true and the user hasn't provided a corso.toml file.

**Comment by vkamra** [comment] 2023-07-20 17:42
Fixed with #3860 . We also released v0.11.1 with this fix.

**Closed by vkamra** 2023-07-20 17:42 UTC
Labels: bug
