### ISSUE TITLE
CI Test Failure: Http transport connection broken

### ISSUE THREAD

**Issue by ryanfkeepers** [alcionai/corso#2707] opened 2023-03-06 16:36 UTC
## Issue
We're seeing intermittent failures in both GH and local integration testing with erroneous responses from graph api.

Link to one such failed test: https://github.com/alcionai/corso/actions/runs/4298555994/jobs/7492799605

Error Output:
```
# GH:
Delete "https://graph.microsoft.com/v1.0/users/***/mailFolders/***": net/http: HTTP/1.x transport connection broken: malformed HTTP response "0"

# Local:
2023/03/03 17:26:21 Unsolicited response received on idle HTTP channel starting with "0\r\n\r\n"; err=<nil>
```

Response payload dump from linked error:
```
HTTP/1.1 204 No Content
Transfer-Encoding: chunked
Cache-Control: private
Client-Request-Id: e276360f-029a-456d-8879-e625bfacf1c0
Date: Wed, 01 Mar 2023 00:19:48 GMT
Request-Id: 8eb66e4a-4797-4623-96de-3f977020f273
Strict-Transport-Security: max-age=31536000
X-Ms-Ags-Diagnostic: {"ServerInfo":{"DataCenter":"East US","Slice":"E","Ring":"5","ScaleUnit":"005","RoleInstance":"MN1PEPF00002F6D"}}

0


```

**Comment by meain** [comment] 2023-03-20 09:35
https://groups.google.com/g/golang-nuts/c/ItC745n3MrI seems to be what we are running into. `Transfer-Encoding` is set to `chunked` in the graph response for pretty much all endpoints. Also looking at the previous request printed out by the CI logs, it looks like a 204 which might be the problem, maybe. ([related](https://github.com/golang/go/issues/4454)).

https://github.com/microsoftgraph/msgraph-sdk-java-core/issues/138 could also be related.

**Comment by meain** [comment] 2023-03-24 10:45
The problem seem to be that Microsoft server is sending `0\r\n\r\n` for `204 No Content` even thought it should be **no content**. *The random string is the end/empty marker for `Transfer-Encoding: chunked` which is somehow always set even if this request is not chunked.*

https://github.com/golang/go/issues/19895
https://www.rfc-editor.org/rfc/rfc9110.html#section-15.3.5-5

**Comment by meain** [comment] 2023-03-27 10:31
Good news and bad news.
Bad news: Don't think we can fix it on our end
Good new: This won't happen during actual backups as this only affects responses returning 204 which is only delete requests which we are not doing during corso backup

**Comment by vkamra** [comment] 2023-03-27 18:06
@meain - why is https://github.com/microsoft/kiota-http-go/blob/84dfb51123886b88515e27bfa6da614fcd9629e9/nethttp_request_adapter.go#L311 not getting triggered here?

**Comment by meain** [comment] 2023-03-28 05:31
>  why is [microsoft/kiota-http-go@`84dfb51`/nethttp_request_adapter.go#L311](https://github.com/microsoft/kiota-http-go/blob/84dfb51123886b88515e27bfa6da614fcd9629e9/nethttp_request_adapter.go#L311) not getting triggered here?

IIUC this does get triggered and we do get a nil response back, but the problem is that in the next request golang tries to read the response stream and gets the `0\r\n\r\n` left from prev response when it is expecting response headers for the new request.

**Comment by ashmrtn** [comment] 2023-03-28 15:19
shouldn't the [defered](https://github.com/microsoft/kiota-http-go/blob/84dfb51123886b88515e27bfa6da614fcd9629e9/nethttp_request_adapter.go#L306) `purge` call empty the body reader so it doesn't have that issue though?

**Comment by ryanfkeepers** [comment] 2023-03-28 16:42
Sidestepping cause analysis, since deletes are rare and primarily in use for testing, could this be fixed by creating a new http client for each delete calls?

**Comment by meain** [comment] 2023-03-28 16:46
> Sidestepping cause analysis, since deletes are rare and primarily in use for testing, could this be fixed by creating a new http client for each delete calls?

Yup, that should ideally solve it, one per call.

**Comment by ryanfkeepers** [comment] 2023-03-28 16:58
> Yup, that should ideally solve it.

Okay, PR inc.

**Comment by meain** [comment] 2023-03-31 17:56
Closed via https://github.com/alcionai/corso/pull/2970 . We can rework this once/if we have a fix from Microsoft.

**Closed by meain** 2023-03-31 17:56 UTC
Labels: bug, tests, upstream
